/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Herencia;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author JABER
 */
public class ventanaprincipal extends javax.swing.JFrame {

    BotonContador btnBotonA;
    BotonContador btnBotonB;

    /**
     * Creates new form ventanaprincipal
     */
    public ventanaprincipal() {
        initComponents();
        CreacionVentana();
    }

    public void CreacionVentana() {
        this.setTitle("Ejercicio de Herencia");
        this.setSize(250, 300);
        this.getContentPane().setLayout(null); // Asegurar layout nulo para posicionamiento absoluto

        // Construcción y posicionamiento de los botones contadores
        btnBotonA = new BotonContador(); // Corregido: BotonContador -> JButton (asumiendo que no existe la clase personalizada)
        btnBotonA.setText("Botón A"); // Mejor: acento en "Botón"
        btnBotonA.setBounds(10, 10, 100, 30);
        this.getContentPane().add(btnBotonA);

        btnBotonB = new BotonContador(); // Corregido: BotonContador -> JButton
        btnBotonB.setText("Botón B");
        btnBotonB.setBounds(130, 10, 100, 30);
        this.getContentPane().add(btnBotonB);

        btnBotonA.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pulsacionBotonA(evt);
            }
        });

        btnBotonB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pulsacionBotonB(evt);
            }
        });
    }

    public void pulsacionBotonA(ActionEvent evt) {
    btnBotonA.incrementa();

    }

    public void pulsacionBotonB(ActionEvent evt) {
        btnBotonB.incrementa();
    }
    
    private void btnVerPulsacionesActionPerformed(java.awt.event.ActionEvent evt) { 
    String info;

    info = "El botón A se ha pulsado " + btnBotonA.getPulsaciones() + "\n"; 
    info = info +  "El botón B se ha pulsado " + btnBotonB.getPulsaciones() + "\n"; 
    
   JOptionPane.showMessageDialog(this, info);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
